
services:
  tic-tac-toe:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=localhost
      - DEBUG=true
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped
